### ISSUE TITLE
cannot deploy jenkins-cluster-ephemeral

### ISSUE THREAD

**Issue by ganrad** [sabre1041/ose-jenkins-cluster#2]
When I try to deploy Jenkins master + slave in OpenShift Ent. 3.1, the 'build' pod for jenkins master does not even start.  The build pod for jenkins slave finishes & a jenkins slave pod starts ok.
Command - $oc new-app --template=jenkins-cluster-ephemeral

Question:
Is the default value for parameter JENKINS_IMAGE_TAG ('jenkins:1.609-15') correct ? I tried running the 'new-app' command by passing a value of 'jenkins:latest' but then the build fails while running the sed command -> sed: can't read /opt/openshift/configuration/config.xml: No such file or directory.  Not sure if the jenkins:latest docker image contains this file ??

Any idea where I am going wrong ? Thanks.

**Comment by sabre1041** [comment]
@ganrad Templates were updated to account for tracking all tags. Would you be able to pull down the latest changes from the repository and replace the existing template with the new one and attempt to create the application again?

**Comment by ganrad** [comment]
Thanks Andy.  I have run into a few n/w'ing issues on my local OSE instance. Once I have it resolved, I will redeploy the jenkins-cluster template.  Will let you know.
Quick ? - I went thru the updates to the template files.  Do we really need to specify the 'kind:from' data in the dockerStrategy stanza/section (below).  
"from": {
                            "kind": "ImageStreamTag",
                            "name": "${JENKINS_IMAGE_TAG}"
                        }
The dockerfile anyways specifies the co-ordinates for the base image in the 'From' cmd.  So can we not leave the strategy stanza empty as - dockerStrategy {}?  Is there a need to create a separate ImageStreamTag and then specify the tag in the dockerStrategy section?

**Comment by sabre1041** [comment]
@ganrad the from is not required, however specifying an imagestream is recommended as to track modifications from upstream repositories (such as security patches or updates)

At build time, the FROM statement in the Dockerfile is automatically replace with information from the ImageStream

**Comment by ganrad** [comment]
Thanks for the explaining how the ImageStreamTag in the buildConfig would be used.  Makes sense.  Also, I deployed the jenkins-cluster-ephemeral template to my local OSE instance today.  The docker builds for both the Jenkins master + slaves completed fine.  And finally the jenkins master + slaves pods started.  I was able to run a few jenkins jobs via the slaves as well.  Thanks.

**Comment by sabre1041** [comment]
@ganrad glad to hear it!

closing the issue

**Comment by NadezhdaBaranova** [comment]
Hello sabre1041!
I've got the same error building master using your ephemeral template:
**error instantiating Build from BuildConfig nbjenkins/jenkins: Error resolving ImageStreamTag ose-jenkins:1.609-15 in namespace nbjenkins: unable to find latest tagged image**

If I change my Build to use "**ose-jenkins:latest**" I've got the error **sed: "can't read /opt/openshift/configuration/config.xml: No such file or directory"**.

Please, advise.
