### ISSUE TITLE
one of maxSurge or maxUnavailable must be specified

### ISSUE THREAD

**Issue by itewk** [sabre1041/ose-jenkins-cluster#6]
When I try to run a build of the jenkins-slave i get the following:

```
[root@master-1 ~]# oc logs jenkins-slave-2-deploy                                                                       
I0320 14:40:48.492010       1 deployer.go:198] Deploying from jenkins/jenkins-slave-1 to jenkins/jenkins-slave-2 (replicas: 0)                                                                                                                  
I0320 14:40:49.634951       1 rolling.go:232] RollingUpdater: Continuing update with existing controller jenkins-slave-2.                                                                                                                       
F0320 14:40:49.678825       1 deployer.go:65] one of maxSurge or maxUnavailable must be specified  
```

**Comment by sabre1041** [comment]
@itewk I've updated the blog post to indicate that the deploymentConfig should be removed instead of scaling down the number of running instances to avoid seeing the issue that you are experiencing.

If this is an acceptable resolution, would you be able to close this issue?

Thanks

**Comment by itewk** [comment]
Wasn't there an alternative option of setting the replica count to 0? Or was it something else. I know i got this working without removing the DC. Maybe worth listing both options?

**Comment by sabre1041** [comment]
Scaling down to a replica count of 0 was the primary cause of the issue. The solution is to keep at least 1 pod running for the rolling deployment to work. If the Kubernetes plugin is to be used as the only method for spinning up slaves, the deploymentConfig should be removed

**Comment by itewk** [comment]
Hmm. I could have sworn I found a way to get it working with 0 replicas deployed but still with the DC. But in any case. yeah I can close this.
